# Generated by Django 2.1.4 on 2020-02-16 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_articlepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论')),
                ('likes', models.IntegerField(default=0, verbose_name='顶')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('author_id', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='谁评论的')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ArticlePost', verbose_name='文章的id')),
            ],
        ),
    ]
